# Generated by Django 6.0.5 on 2026-05-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
