# Generated by Django 6.0.5 on 2026-05-22 13:20

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("participation", "0004_ticket_tiers_and_custom_forms"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="networking_opt_in",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customformfield",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="registrationanswer",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="tickettier",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="volunteershift",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
