# Generated by Django 6.0.5 on 2026-05-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("participation", "0005_registration_networking_opt_in_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="waitlistentry",
            name="offered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="waitlistentry",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("offered", "Offered"), ("expired", "Expired")],
                default="pending",
                max_length=20,
            ),
        ),
    ]
